name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: 0 0 * * 0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Packages
        run: npm install
      - name: Lint
        run: npm run -s lint

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        eslint: [7]
        node: [14]
        include:
          # On other platforms
          - eslint: 7
            node: 14
            os: windows-latest
          - eslint: 7
            node: 14
            os: macos-latest
          # On old Node.js versions
          - eslint: 7
            node: 12
            os: ubuntu-latest
          - eslint: 7
            node: 10
            os: ubuntu-latest
          # On old ESLint versions
          - eslint: 6
            node: 14
            os: ubuntu-latest
          - eslint: 5
            node: 14
            os: ubuntu-latest
          # On the minimum supported ESLint/Node.js version
          - eslint: 5
            node: 6.14
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js v${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install NPM
        if: ${{ matrix.node >= 6 && matrix.node < 7 }}
        run: |
          npm install --global npm@^6.0.0
      - name: Install Packages
        run: |
          npm install
      - name: Install ESLint ${{ matrix.eslint }}
        run: npm install --no-save eslint@${{ matrix.eslint }}
      - name: Build
        run: npm run -s build
      - name: Test
        run: npm run -s test:mocha
      - name: Send Coverage
        run: npm run -s codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
